function EditProfileModal({ open, onClose }) {
      if (!open) return null;

        return (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4">

                      <div className="w-full max-w-lg rounded-2xl bg-slate-900 border border-slate-800 p-6">

                              <div className="flex items-center justify-between">

                                        <h2 className="text-2xl font-bold text-white">
                                                    Edit Profile
                                                              </h2>

                                                                        <button
                                                                                    onClick={onClose}
                                                                                                className="text-slate-400 hover:text-white text-2xl"
                                                                                                          >
                                                                                                                      ✕
                                                                                                                                </button>

                                                                                                                                        </div>

                                                                                                                                                <form className="mt-6 space-y-4">

                                                                                                                                                          <input
                                                                                                                                                                      type="text"
                                                                                                                                                                                  placeholder="Username"
                                                                                                                                                                                              className="w-full rounded-xl bg-slate-950 border border-slate-700 px-4 py-3 text-white placeholder:text-slate-500 outline-none focus:border-cyan-500"
                                                                                                                                                                                                        />

                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                              type="text"
                                                                                                                                                                                                                                          placeholder="Full Name"
                                                                                                                                                                                                                                                      className="w-full rounded-xl bg-slate-950 border border-slate-700 px-4 py-3 text-white placeholder:text-slate-500 outline-none focus:border-cyan-500"
                                                                                                                                                                                                                                                                />

                                                                                                                                                                                                                                                                          <textarea
                                                                                                                                                                                                                                                                                      rows="4"
                                                                                                                                                                                                                                                                                                  placeholder="Bio"
                                                                                                                                                                                                                                                                                                              className="w-full rounded-xl bg-slate-950 border border-slate-700 px-4 py-3 text-white placeholder:text-slate-500 outline-none focus:border-cyan-500 resize-none"
                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                              type="text"
                                                                                                                                                                                                                                                                                                                                                          placeholder="Location"
                                                                                                                                                                                                                                                                                                                                                                      className="w-full rounded-xl bg-slate-950 border border-slate-700 px-4 py-3 text-white placeholder:text-slate-500 outline-none focus:border-cyan-500"
                                                                                                                                                                                                                                                                                                                                                                                />

                                                                                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                                                                                      type="url"
                                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="Website"
                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full rounded-xl bg-slate-950 border border-slate-700 px-4 py-3 text-white placeholder:text-slate-500 outline-none focus:border-cyan-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                              type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="w-full rounded-xl bg-cyan-500 py-3 font-bold text-black hover:bg-cyan-400 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Save Changes
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
        );
    }

    export default EditProfileModal;