import { useState } from "react";

function Register() {
  const [form, setForm] = useState({
      username: "",
          fullName: "",
              email: "",
                  password: "",
                    });

                      function handleChange(e) {
                          setForm({
                                ...form,
                                      [e.target.name]: e.target.value,
                                          });
                                            }

                                              function handleSubmit(e) {
                                                  e.preventDefault();

                                                      console.log(form);
                                                        }

                                                          return (
                                                              <div style={styles.container}>
                                                                    <form style={styles.form} onSubmit={handleSubmit}>
                                                                            <h1>LINKUP.HUB</h1>
                                                                                    <p>Create your account 🚀</p>

                                                                                            <input
                                                                                                      type="text"
                                                                                                                name="username"
                                                                                                                          placeholder="Username"
                                                                                                                                    onChange={handleChange}
                                                                                                                                              required
                                                                                                                                                      />

                                                                                                                                                              <input
                                                                                                                                                                        type="text"
                                                                                                                                                                                  name="fullName"
                                                                                                                                                                                            placeholder="Full Name"
                                                                                                                                                                                                      onChange={handleChange}
                                                                                                                                                                                                                required
                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                          type="email"
                                                                                                                                                                                                                                                    name="email"
                                                                                                                                                                                                                                                              placeholder="Email"
                                                                                                                                                                                                                                                                        onChange={handleChange}
                                                                                                                                                                                                                                                                                  required
                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                            type="password"
                                                                                                                                                                                                                                                                                                                      name="password"
                                                                                                                                                                                                                                                                                                                                placeholder="Password"
                                                                                                                                                                                                                                                                                                                                          onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                    required
                                                                                                                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                                                                                                                    <button type="submit">
                                                                                                                                                                                                                                                                                                                                                                              Create Account
                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                            </form>
                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                  const styles = {
                                                                                                                                                                                                                                                                                                                                                                                                    container: {
                                                                                                                                                                                                                                                                                                                                                                                                        display: "flex",
                                                                                                                                                                                                                                                                                                                                                                                                            justifyContent: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                alignItems: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                    minHeight: "100vh",
                                                                                                                                                                                                                                                                                                                                                                                                                        background: "#f5f5f5",
                                                                                                                                                                                                                                                                                                                                                                                                                          },

                                                                                                                                                                                                                                                                                                                                                                                                                            form: {
                                                                                                                                                                                                                                                                                                                                                                                                                                display: "flex",
                                                                                                                                                                                                                                                                                                                                                                                                                                    flexDirection: "column",
                                                                                                                                                                                                                                                                                                                                                                                                                                        gap: "15px",
                                                                                                                                                                                                                                                                                                                                                                                                                                            width: "320px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: "30px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                    background: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                            boxShadow: "0 0 15px rgba(0,0,0,.1)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default Register;