import { useState } from "react";

function Register() {
  const [form, setForm] = useState({
      username: "",
          fullName: "",
              email: "",
                  password: "",
                    });

                      const [loading, setLoading] = useState(false);

                        function handleChange(e) {
                            setForm({
                                  ...form,
                                        [e.target.name]: e.target.value,
                                            });
                                              }

                                                async function handleSubmit(e) {
                                                    e.preventDefault();

                                                        setLoading(true);

                                                            const { error } = await register({
                                                                  email: form.email,
                                                                        password: form.password,
                                                                              username: form.username,
                                                                                    fullName: form.fullName,
                                                                                        });

                                                                                            setLoading(false);

                                                                                                if (error) {
                                                                                                      alert(error.message);
                                                                                                            return;
                                                                                                                }

                                                                                                                    alert(
                                                                                                                          "🎉 Account created successfully! Check your email if email confirmation is enabled."
                                                                                                                              );

                                                                                                                                  setForm({
                                                                                                                                        username: "",
                                                                                                                                              fullName: "",
                                                                                                                                                    email: "",
                                                                                                                                                          password: "",
                                                                                                                                                              });
                                                                                                                                                                }

                                                                                                                                                                  return (
                                                                                                                                                                      <div style={styles.container}>
                                                                                                                                                                            <form style={styles.form} onSubmit={handleSubmit}>

                                                                                                                                                                                    <h1>LINKUP.HUB</h1>

                                                                                                                                                                                            <p>Create your account 🚀</p>

                                                                                                                                                                                                    <input
                                                                                                                                                                                                              type="text"
                                                                                                                                                                                                                        name="username"
                                                                                                                                                                                                                                  placeholder="Username"
                                                                                                                                                                                                                                            value={form.username}
                                                                                                                                                                                                                                                      onChange={handleChange}
                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                          type="text"
                                                                                                                                                                                                                                                                                                    name="fullName"
                                                                                                                                                                                                                                                                                                              placeholder="Full Name"
                                                                                                                                                                                                                                                                                                                        value={form.fullName}
                                                                                                                                                                                                                                                                                                                                  onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                      type="email"
                                                                                                                                                                                                                                                                                                                                                                                name="email"
                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Email"
                                                                                                                                                                                                                                                                                                                                                                                                    value={form.email}
                                                                                                                                                                                                                                                                                                                                                                                                              onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                        required
                                                                                                                                                                                                                                                                                                                                                                                                                                />

                                                                                                                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                            name="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      placeholder="Password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={form.password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {loading ? "Creating..." : "Create Account"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const styles = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                container: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    display: "flex",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        justifyContent: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            alignItems: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                minHeight: "100vh",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    background: "#f5f5f5",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        form: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            display: "flex",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                flexDirection: "column",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    gap: "15px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        width: "320px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            padding: "30px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                background: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        boxShadow: "0 0 15px rgba(0,0,0,.1)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default Register;