import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Link, useNavigate } from "react-router-dom";
import toast from "react-hot-toast";

import { loginSchema } from "../schemas/loginSchema";
import { loginUser } from "../../../services/authService";

function LoginForm() {
  const navigate = useNavigate();
    const [loading, setLoading] = useState(false);

      const {
          register,
              handleSubmit,
                  formState: { errors },
                    } = useForm({
                        resolver: zodResolver(loginSchema),
                          });

                            async function onSubmit(values) {
                                try {
                                      setLoading(true);

                                            await loginUser(values.email, values.password);

                                                  toast.success("🎉 Welcome back!");

                                                        navigate("/");
                                                            } catch (error) {
                                                                  toast.error(error.message);
                                                                      } finally {
                                                                            setLoading(false);
                                                                                }
                                                                                  }

                                                                                    return (
                                                                                        <div className="min-h-screen flex items-center justify-center bg-slate-950 px-4">
                                                                                              <div className="w-full max-w-md rounded-2xl bg-slate-900 border border-slate-700 p-8 shadow-xl">

                                                                                                      <h1 className="text-4xl font-bold text-center text-cyan-400">
                                                                                                                LINKUP.HUB
                                                                                                                        </h1>

                                                                                                                                <p className="text-center text-slate-400 mt-2">
                                                                                                                                          Welcome back 👋
                                                                                                                                                  </p>

                                                                                                                                                          <form
                                                                                                                                                                    onSubmit={handleSubmit(onSubmit)}
                                                                                                                                                                              className="space-y-5 mt-8"
                                                                                                                                                                                      >
                                                                                                                                                                                                <div>
                                                                                                                                                                                                            <input
                                                                                                                                                                                                                          type="email"
                                                                                                                                                                                                                                        {...register("email")}
                                                                                                                                                                                                                                                      placeholder="Email"
                                                                                                                                                                                                                                                                    className="w-full rounded-lg bg-slate-800 border border-slate-700 px-4 py-3 text-white outline-none focus:border-cyan-500"
                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                            <p className="text-red-400 text-sm mt-1">
                                                                                                                                                                                                                                                                                                          {errors.email?.message}
                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                    type="password"
                                                                                                                                                                                                                                                                                                                                                                                  {...register("password")}
                                                                                                                                                                                                                                                                                                                                                                                                placeholder="Password"
                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full rounded-lg bg-slate-800 border border-slate-700 px-4 py-3 text-white outline-none focus:border-cyan-500"
                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-red-400 text-sm mt-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    {errors.password?.message}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="w-full rounded-lg bg-cyan-500 hover:bg-cyan-400 py-3 font-semibold text-slate-950 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {loading ? "Signing In..." : "Login"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-center text-slate-400 mt-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Don't have an account?{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            to="/register"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="text-cyan-400 hover:underline"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Register
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default LoginForm;